In [1]:
import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(0,10, [2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

# Méthodes ndarray

In [18]:
#Oppération aritmétique et de trie sur une matrice de donner ou Tableaun à N dimension

In [5]:
A.sum(axis=0)

array([ 8,  7, 12])

In [6]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27], dtype=int32)

In [7]:
A.prod()

0

In [8]:
A.cumprod()

array([5, 0, 0, 0, 0, 0], dtype=int32)

In [12]:
A.min(axis=0)

array([3, 0, 3])

In [14]:
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [15]:
A.argsort()

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

# Oppération mathèmatique complexe

In [21]:
#Oppération mathèmatique complexe sur des matrices et tableaux à N dimension

In [ ]:
# Pour toute applictaiton de fonction mathématique complexe appliquè avec le nom du module
np.exp(A)

# Statistiques

In [23]:
#statistiques sur des matrice et tableaux à N dimension

In [24]:
A.mean()#Moyenne du tableaux

4.5

In [25]:
A.std()#écart type

2.9297326385411577

In [26]:
A.var()#variance

8.583333333333334

In [27]:
#Matrice de corrélation
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [28]:
np.corrcoef(A)[0, 1]

-0.5636214801906779

In [29]:
np.unique(A, return_counts = True)
#Le premier Tableau contient toute les entité de ma matrice
#Le deuxième Tableau retourne le nombre de répétition de chaque entité présente dans le tableau

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [30]:
#regénération d'un tableau pour un exercice 
np.random.seed(0)
B = np.random.randint(0,10, [5,5])
B

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [35]:
values, counts = np.unique(B, return_counts=True)

In [37]:
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int64)

In [39]:
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [42]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f"valeur {i} apparait {j} fois")

valeur 0 apparait 1 fois
valeur 2 apparait 1 fois
valeur 1 apparait 2 fois
valeur 4 apparait 2 fois
valeur 6 apparait 2 fois
valeur 3 apparait 3 fois
valeur 5 apparait 3 fois
valeur 9 apparait 3 fois
valeur 7 apparait 4 fois
valeur 8 apparait 4 fois


# NAN Corrections

In [43]:
#Quand nous rencontrons des donner corrompu dans notre tableaux naturel elle seron retrancrite en NaN == Not A Number 

In [44]:
C = np.random.randn(5, 5)
C[0, 2] = np.nan
C[4, 3] = np.nan
C

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [46]:
C.mean()

nan

In [47]:
#Ignorer les valeur nan avec des fonction de numpy

In [48]:
np.nanmean(C)

0.010707879575141632

In [49]:
np.nanstd(C)

1.1017518326683546

In [50]:
np.nanvar(C)

1.213857100788078

In [51]:
#detecter et conter la présence de ses nan

In [52]:
np.isnan(C)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [53]:
#nombre de fois ou nous rencontrons nan dans notre tableau
np.isnan(C).sum()

2

In [54]:
#rapport de nan par apport à la taille de notre tableau
np.isnan(C).sum()/C.size

0.08

In [55]:
#cela signifie que 8 % de nos valeur son des nan

In [56]:
#remplacer les nan de notre tableau grace à un masqu epar des valeur par défaut choisie
C[np.isnan(C)] = 0
C

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

# Algebre Linéaire

In [58]:
D = np.ones((2, 3))
E = np.ones((3, 2))

In [59]:
D

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
E

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
#Transposition de matrice 
D.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
#Le produit de deux matrice de données
D.dot(E)

array([[3., 3.],
       [3., 3.]])

In [64]:
E.dot(D)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [65]:
 F = np.random.randint(0, 10, [3, 3])

In [66]:
F

array([[3, 5, 9],
       [4, 4, 6],
       [4, 4, 3]])

In [67]:
#calculer le déterminant de ma matrice F
np.linalg.det(F)

23.999999999999993

In [68]:
#Inversion de ma matrice 
np.linalg.inv(F)

array([[-0.5       ,  0.875     , -0.25      ],
       [ 0.5       , -1.125     ,  0.75      ],
       [-0.        ,  0.33333333, -0.33333333]])

# Exercice

Standardisez la matrice G sur chaque colonne.

Résultat : chaque colonne doit avoir moyenne = 0 et écart type = 1

Calcule : G' = (G - mean(G)) / std(G)

In [70]:
np.random.seed(0)
G = np.random.randint(0, 100, [10, 5])
G

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [83]:
colone1 = G[:, 0]

In [89]:
G[:, 0] = (colone1 - colone1.mean())/colone1.std()
G

array([[ 0, 47, 64, 67, 67],
       [-1, 83, 21, 36, 87],
       [ 1, 88, 88, 12, 58],
       [ 0, 39, 87, 46, 88],
       [ 1, 37, 25, 77, 72],
       [-1, 20, 80, 69, 79],
       [ 0, 64, 82, 99, 88],
       [ 0, 29, 19, 19, 14],
       [ 0, 32, 65,  9, 57],
       [ 0, 31, 74, 23, 35]])