# Broadcasting

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0, 10, [4,1])
B = np.ones((1, 3))

In [3]:
A

array([[5],
       [0],
       [3],
       [3]])

In [4]:
B

array([[1., 1., 1.]])

# Explication

Le broadcasting permet d'étendre des matrices pour permettre de calculer des matrices impossible normalement 

exemple :

In [5]:
A + B

array([[6., 6., 6.],
       [1., 1., 1.],
       [4., 4., 4.],
       [4., 4., 4.]])

Tout en respectant certaine condition applicable au matrice 

exemple :

In [6]:
A = np.random.randint(0, 10, [4,2])
A

array([[7, 9],
       [3, 5],
       [2, 4],
       [7, 6]])

In [7]:
B

array([[1., 1., 1.]])

In [8]:
A + B

ValueError: operands could not be broadcast together with shapes (4,2) (1,3) 

### Information exception

_____

Correct :
(1, 4)
(10, 1)

Incorrect :
(2, 3)
(10, 5)

##### ça permet d'étendre une matrice au dimension de l'autre pour pouvoir la calculer

Applicable seulement si les taille des matrice sont identique au nombre de colonne et de ligne ou si le nombre différent d'une des matrice = 1


# Inconvéniant du Broadcasting

lors de matrice de dimention incomplète :

(5, ) 

Le programme estimera que le 5 est le dernier élément de la taille de ma matrice 

exemple :

In [13]:
A = np.random.randint(0,10, [4, 1])
B = np.ones(5,)

In [11]:
A

array([[8],
       [8],
       [1],
       [6]])

In [14]:
B

array([1., 1., 1., 1., 1.])

In [16]:
A + B

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9.],
       [2., 2., 2., 2., 2.]])

### Information sur la règles
________

On pourrait penser que ça ne fonctionnerais pas vu que les taille respective des deux tableaux ne respecte pas les règles :

(4, 1)
(5, )

mais il considére le (5,) comme le dernière élèment de votre .shape

Donc il est important de redimensionner vos élément pour avoir un une shape comme ceci :

(5, 1)

Ce qui évitera tout bug dans le future 