In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0,10, [2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

# Méthodes ndarray

In [3]:
#Oppération aritmétique et de trie sur une matrice de donner ou Tableaun à N dimension

In [4]:
A.sum(axis=0)

array([ 8,  7, 12])

In [5]:
A.cumsum()

array([ 5,  5,  8, 11, 18, 27], dtype=int32)

In [6]:
A.prod()

0

In [7]:
A.cumprod()

array([5, 0, 0, 0, 0, 0], dtype=int32)

In [8]:
A.min(axis=0)

array([3, 0, 3])

In [9]:
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [10]:
A.argsort()

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

# Oppération mathèmatique complexe

In [11]:
#Oppération mathèmatique complexe sur des matrices et tableaux à N dimension

In [12]:
# Pour toute applictaiton de fonction mathématique complexe appliquè avec le nom du module
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

# Statistiques

In [13]:
#statistiques sur des matrice et tableaux à N dimension

In [14]:
A.mean()#Moyenne du tableaux

4.5

In [15]:
A.std()#écart type

2.9297326385411577

In [16]:
A.var()#variance

8.583333333333334

In [17]:
#Matrice de corrélation
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [18]:
np.corrcoef(A)[0, 1]

-0.5636214801906779

In [19]:
np.unique(A, return_counts = True)
#Le premier Tableau contient toute les entité de ma matrice
#Le deuxième Tableau retourne le nombre de répétition de chaque entité présente dans le tableau

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [20]:
#regénération d'un tableau pour un exercice 
np.random.seed(0)
B = np.random.randint(0,10, [5,5])
B

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [21]:
values, counts = np.unique(B, return_counts=True)

In [22]:
counts.argsort()

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int64)

In [23]:
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [24]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f"valeur {i} apparait {j} fois")

valeur 0 apparait 1 fois
valeur 2 apparait 1 fois
valeur 1 apparait 2 fois
valeur 4 apparait 2 fois
valeur 6 apparait 2 fois
valeur 3 apparait 3 fois
valeur 5 apparait 3 fois
valeur 9 apparait 3 fois
valeur 7 apparait 4 fois
valeur 8 apparait 4 fois


# NAN Corrections

Quand nous rencontrons des donner corrompu dans notre tableaux naturel elles seront retrancrite en NaN == Not A Number 

In [26]:
C = np.random.randn(5, 5)
C[0, 2] = np.nan
C[4, 3] = np.nan
C

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [27]:
C.mean()

nan

In [28]:
#Ignorer les valeur nan avec des fonction de numpy

In [29]:
np.nanmean(C)

0.010707879575141632

In [30]:
np.nanstd(C)

1.1017518326683546

In [31]:
np.nanvar(C)

1.213857100788078

In [32]:
#detecter et conter la présence de ses nan

In [33]:
np.isnan(C)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [34]:
#nombre de fois ou nous rencontrons nan dans notre tableau
np.isnan(C).sum()

2

In [35]:
#rapport de nan par apport à la taille de notre tableau
np.isnan(C).sum()/C.size

0.08

In [36]:
#cela signifie que 8 % de nos valeur son des nan

In [37]:
#remplacer les nan de notre tableau grace à un masqu epar des valeur par défaut choisie
C[np.isnan(C)] = 0
C

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

# Algebre Linéaire

In [38]:
D = np.ones((2, 3))
E = np.ones((3, 2))

In [39]:
D

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
E

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
#Transposition de matrice 
D.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
#Le produit de deux matrice de données
D.dot(E)

array([[3., 3.],
       [3., 3.]])

In [43]:
E.dot(D)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [44]:
 F = np.random.randint(0, 10, [3, 3])

In [45]:
F

array([[3, 5, 9],
       [4, 4, 6],
       [4, 4, 3]])

In [46]:
#calculer le déterminant de ma matrice F
np.linalg.det(F)

23.999999999999993

In [47]:
#Inversion de ma matrice 
np.linalg.inv(F)

array([[-0.5       ,  0.875     , -0.25      ],
       [ 0.5       , -1.125     ,  0.75      ],
       [-0.        ,  0.33333333, -0.33333333]])

# Exercice

Standardisez la matrice G sur chaque colonne.

Résultat : chaque colonne doit avoir moyenne = 0 et écart type = 1

Calcule : G' = (G - mean(G)) / std(G)

### Mes Calcules

In [48]:
np.random.seed(0)
G = np.random.randint(0, 100, [10, 5])
G

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [49]:
colone1 = G[:, 0]
colone2 = G[:, 1]
colone3 = G[:, 2]
colone4 = G[:, 3]
colone5 = G[:, 4]

In [50]:
colone1 = (colone1 - colone1.mean())/colone1.std()
colone2 = (colone2 - colone2.mean())/colone2.std()
colone3 = (colone3 - colone3.mean())/colone3.std()
colone4 = (colone4 - colone4.mean())/colone4.std()
colone5 = (colone5 - colone5.mean())/colone5.std()

In [51]:
G[:, 0] = colone1
G[:, 1] = colone2
G[:, 2] = colone3
G[:, 3] = colone4
G[:, 4] = colone5
G

array([[ 0,  0,  0,  0,  0],
       [-1,  1, -1,  0,  0],
       [ 1,  1,  1, -1,  0],
       [ 0,  0,  0,  0,  1],
       [ 1,  0, -1,  1,  0],
       [-1, -1,  0,  0,  0],
       [ 0,  0,  0,  1,  1],
       [ 0,  0, -1,  0, -2],
       [ 0,  0,  0, -1,  0],
       [ 0,  0,  0,  0, -1]])

### Correction

In [52]:
np.random.seed(0)
G_correction = np.random.randint(0, 100, [10, 5])
G_correction

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [53]:
Result = (G_correction - G_correction.mean(axis=0)) / G_correction.std(axis=0)
Result

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [54]:
Result.mean(axis=0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [55]:
Result.std(axis=0)

array([1., 1., 1., 1., 1.])

### Mon Erreur

mon erreur à été de diviser l'oppération par colonne et de ne pas prendre en compte le fait que je devais me concentré que sur l'axe 0 et non sur les axes 1 par 1

Ce que je dois retenir est que lors d'oppération de se type vaut mieux recrée un nouveau tableau